name: Deploy to GitHub Pages

# Trigger deployment on any push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Adjust the version as needed

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the site (this will also perform the static export)
      - name: Build the Next.js Site
        run: npm run build

      # Step 5: Deploy the contents of the 'out' folder to GitHub Pages
      - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
